server:
    port: 8081

spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        virtual-host: /
        # 确保消息成功发送到交换器
        publisher-confirm-type: correlated
        # 开启消息返回
        publisher-returns: true
        template:
            # 消息投递失败返回客户端，该参数与publisher-returns同时配合使用
            mandatory: true
            retry:
                enabled: false
                initial-interval: 1000ms
                max-attempts: 3
                max-interval: 1000ms
                multiplier: 2
    main:
        allow-circular-references: true
