server:
    port: 8081

spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        virtual-host: /
        # 确保消息成功发送到交换器
        publisher-confirm-type: correlated
        template:
            retry:
                enabled: false
                initial-interval: 1000ms
                max-attempts: 3
                max-interval: 1000ms
                multiplier: 2
#        # 可以确保消息在未被队列接收时返回
#        publisher-returns: true
#        # 该参数与publisher-returns同时配合使用
#        template:
#            mandatory: true