server:
    port: 8081
spring:
    datasource:   # 数据源的相关配置
        url: jdbc:mysql://localhost:3306/mall-dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
        username: root
        password: fx1212
    elasticsearch:
        rest:
            uris: http://192.168.156.138:9200,http://192.168.156.139:9200,http://192.168.156.140:9200


