spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        virtual-host: /
mq:
    queueBinding:
        queue: prod_queue_pay
        exchange:
            name: exchange_prod_pay
        key: prod_pay
