spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        virtual-host: /
        listener:
            simple:
                #  采用手动应答
                acknowledge-mode: manual
                #  当前监听容器数
                concurrency: 10
                #  最大数
                max-concurrency: 10
                #  是否支持重试
                retry:
                    enabled: false
server:
    port: 8082