server:
    port: 8081

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: fx1212
        url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai