server:
    port: 80

spring:
    datasource:                                           # 数据源的相关配置
        url: jdbc:mysql://localhost:3306/mall-dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
        password: fx1212