server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: fx1212
        driver-class-name: com.mysql.cj.jdbc.Driver


management:
    endpoints:
        web:
            exposure:
                include: beans
